name: gobright

services:

  db:
    image: postgres:15.7
    # restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
    - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    ports:
      - 8080:8080

  gobright:
    image: bwzgobright:0.1
    depends_on:      
      - db


volumes:
  db-data:
